import "./blocks/container/script";
import "./blocks/team-member/script";
import "./blocks/testimonial/script";
import "./blocks/separator/script";
import "./blocks/number-box/script";
import "./blocks/post-grid/script";
import "./blocks/drop-cap/script";
import "./blocks/notification/script";
import "./blocks/share-icons/script";
import "./blocks/author-profile/script";
import "./blocks/cta/script";
import "./blocks/spacer-divider/script";
import "./blocks/accordion/script";
import "./blocks/blockquote/script";
import "./blocks/icon-list/script";
import "./blocks/count-up/script";
import "./blocks/button/script";

import "./blocks/newsletter/script";
